# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-07-06 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='job',
            field=models.CharField(default=True, max_length=120),
        ),
    ]
